name: Packer Build and Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:  # manual execution

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup Packer
        uses: hashicorp/setup-packer@main
        with:
          version: latest

      - name: Packer Init
        run: packer init golden-ami.pkr.hcl

      - name: Validate Template
        run: packer validate -syntax-only golden-ami.pkr.hcl

      - name: Packer Build
        run: packer build -color=false -on-error=cleanup golden-ami.pkr.hcl